name: ckb-did-plc-utils

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Install ckb-debugger
      shell: bash
      run: |
        wget 'https://github.com/nervosnetwork/ckb-standalone-debugger/releases/download/v0.200.1/ckb-debugger_v0.200.1_x86_64-unknown-linux-gnu.tar.gz'
        tar xzvf ckb-debugger_v0.200.1_x86_64-unknown-linux-gnu.tar.gz
        mv ckb-debugger ~/.cargo/bin
    - name: Install rust target
      run: rustup target add riscv64imac-unknown-none-elf
    - name: Install pnpm
      shell: bash
      run: npm install -g pnpm

    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Check formatting
      run: cargo fmt -- --check

    - name: Make on-chain script with log
      run: make build CARGO_ARGS="--features enable_log"
    - name: Make on-chain script
      run: make build

    - name: pnpm install
      run: pnpm install

    - name: Generate test vectors
      run: cd tools/gen-test-vectors && pnpm start

    - name: Cargo test
      run: cargo test -p ckb-did-plc-utils-tests
    - name: Pnpm test
      run: pnpm test

